#!/usr/bin/env php
<?php
/* vim: set syntax=php expandtab tabstop=4 shiftwidth=4: */

/**
 * This is a climax application. It is used for development of climax.
 */
require 'src/CLImax.php';
require 'PHPUnit/Autoload.php';
class CLImaxTest extends CLIMaxCommand_Base
{
    public function run($arguments, CLImaxController $cliController)
    {
        array_unshift($arguments, 'fake-phpunit-program');

        $arguments[] = 'test';

        $command = new PHPUnit_TextUI_Command;
        $command->run($arguments);
        return 0;
    }
    public function getDescription($aliases, $argLinker) { return 'Run PHPUnit bootstrapped to this install. Pass whatever arguments you would normally pass to phpunit.'; }
}

class CLImaxSpec extends CLIMaxCommand_Base
{
    public function run($arguments, CLImaxController $cliController)
    {
        array_unshift($arguments, 'fake-phpunit-program');

        // testdox needs to be last (after verbose or other commands)
        if (count($arguments) > 1)
        {
            $last = array_pop($arguments);
            $arguments[] = '--testdox';
            $arguments[] = $last;
        }
        else
        {
            $arguments[] = '--testdox';
        }

        $arguments[] = 'test';

        $command = new PHPUnit_TextUI_Command;
        $command->run($arguments);
        return 0;
    }
    public function getDescription($aliases, $argLinker) { return 'Print out the spec document for the given entity.'; }
}

class CLImaxScaffold extends CLImaxCommand_Base
{
    public function run($arguments, CLImaxController $cliController)
    {
        if (count($arguments) > 1) throw new CLImaxCommand_ArugumentException("scaffold command requires exactly 1 argument: name of file to create.");
        if (count($arguments) === 0)
        {
            $fileName = 'myapp';
        }
        else
        {
            $fileName = $arguments[0];
        }

        $filePath = "./{$fileName}";
        if (file_exists($filePath)) throw new Exception("Specified file {$filePath} already exists.");

        ob_start();
        include dirname(__FILE__) . '/templates/app_scaffold.php';
        $appScaffold = ob_get_contents();
        ob_end_clean();

        file_put_contents($filePath, $appScaffold);
        chmod($filePath, 0777);
        print "Wrote CLImax scaffold app at {$filePath}\n";
        return 0;
    }
    public function getDescription($aliases, $argLinker) { return 'Create a new climax project. Accepts a single argument for the name of the new project; defaults to myapp.'; }
}

// WIRE UP APPLICTION
CLImaxController::create()
                  ->addCommand(new CLImaxTest, array('test'))
                  ->addCommand(new CLImaxSpec, array('spec'))
                  ->addCommand(new CLImaxScaffold, array('scaffold'))
                  ->run($argv, $argc);
