<?php

require_once 'CLImax.php';
require_once 'TestClasses.php';

/**
 * Test class for CLImaxController.
 * Generated by PHPUnit on 2010-09-25 at 20:05:53.
 */
class CLImaxControllerTest extends PHPUnit_Framework_TestCase
{
    /**
     * Generates the argv/argc vars that php creates when using CLI.
     *
     * This is useful for converting a shell command string into argv/argc for testing so it can be passed into run().
     *
     * @param string command
     * @return array Assoc array with argv/argc.
     */
    public function generateArgvArgc($cmd)
    {
        $php = $_SERVER['PHP_COMMAND'];
        $cmd = "{$php} -r 'var_export(array(\"argv\" => \$argv, \"argc\" => \$argc));' {$cmd}";
        $argvArgc = `{$cmd}`;
        $loadArgvArgcCmd = "return {$argvArgc};";
        $argvArgc = eval($loadArgvArgcCmd);
        return $argvArgc;
    }

    /**
     * @testdox Ensure generateArgvArgc() test helper works.
     */
    public function testEnsureArgvArgcGeneratorWorks()
    {
        extract($this->generateArgvArgc("foo bar"));
        $this->assertEquals(array('-', 'foo', 'bar'), $argv);
        $this->assertEquals(3, $argc);

        extract($this->generateArgvArgc("a=b c"));
        $this->assertEquals(array('-', 'a=b', 'c'), $argv);
        $this->assertEquals(3, $argc);
    }

    /**
     * @testdox Has fluent constructor named CLImaxController::create()
     */
    public function testHasFluentStaticConstructorNamedCreate()
    {
        $o = CLImaxController::create();
        $this->assertTrue( $o instanceof CLImaxController );
    }

    /**
     * @testdox Reads default environemnt from $_ENV
     */
    public function testDefaultEnvironment()
    {
        $_ENV = array('foo' => 'bar');

        $o = CLImaxController::create();
        $this->assertTrue($o->hasEnvironment('foo'));
        $this->assertEquals('bar', $o->getEnvironment('foo'));
    }

    public function testMergeEnvironmentDoesNotOverwriteKeysByDefault()
    {
        $_ENV = array('foo' => 'bar');

        $o = CLImaxController::create();

        // test merge w/no overwrite
        $o->mergeEnvironment(array('foo' => 'baz does not overwrite bar without force'));
        $this->assertEquals('bar', $o->getEnvironment('foo'));
    }

    /**
     * @testdox Merge Environment Overwrites Keys if array('overwrite' => true) passed
     */
    public function testMergeEnvironmentOverwritesKeysIfOverwriteEnabled()
    {
        $_ENV = array('foo' => 'bar');

        $o = CLImaxController::create();

        // test merge w/overwrite
        $o->mergeEnvironment(array('foo' => 'baz overwrites bar'), array('overwrite' => true));
        $this->assertEquals('baz overwrites bar', $o->getEnvironment('foo'));
    }

    public function testSetEnvironmentReplacesEntireEnvironment()
    {
        $env = array('foo' => 'bar', 'boo' => 'baz');
        $o = CLImaxController::create();

        // test merge w/no overwrite
        $o->setEnvironment($env);
        $this->assertEquals($env, $o->getEnvironment());
    }

    /**
     * @testdox Calling "cmd" runs default command with no arguments.
     */
    public function testDefaultCommandRunsWithNoArgumentsIfNoCommandsOrArgumentsSpecified()
    {
        extract($this->generateArgvArgc(""));

        $def = $this->getMock('CLIArgRepeater', array('testArguments'));
        $def->expects($this->once())
                        ->method('testArguments')
                        ->with($this->equalTo(array()));
        $o = CLImaxController::create()
                               ->setDefaultCommand($def)
                               ->runTest($argv, $argc);
        $this->assertEquals(0, $o);
    }

    public function testDefaultCommandGetsAllArgumentsIfNoOtherCommandSpecified()
    {
        extract($this->generateArgvArgc("1 2 3 4 5"));

        // ensure proper arguments to run()
        $def = $this->getMock('CLIArgRepeater', array('testArguments'));
        $def->expects($this->once())
                        ->method('testArguments')
                        ->with($this->equalTo(array(1,2,3,4,5)));
        $o = CLImaxController::create()
                               ->setDefaultCommand($def)
                               ->runTest($argv, $argc);
        $this->assertEquals(0, $o);
    }

    public function testDefaultCommandDoesNotRunIfAlwaysRunOptionDisabled()
    {
        extract($this->generateArgvArgc("ar 1 2 3 4 5"));

        $ar = new CLIArgRepeater;
        $def = $this->getMock('CLIArgRepeater', array('run'));
        $def->expects($this->never())
                        ->method('run');
        $o = CLImaxController::create()
                               ->setDefaultCommand($def)
                               ->addCommand($ar, 'ar')
                               ->runTest($argv, $argc);
        $this->assertEquals(0, $o);
    }

    public function testDefaultCommandRunsIfAlwaysRunsOptionEnabled()
    {
        extract($this->generateArgvArgc("ar 1 2 3 4 5"));

        $ar = new CLIArgRepeater;

        // ensure run() is called
        $def = $this->getMock('CLIArgRepeater', array('run'));
        $def->expects($this->once())
                        ->method('run')
                        ->will($this->returnValue(0));
        $o = CLImaxController::create()
                               ->setDefaultCommand($def, array('alwaysRuns' => true))
                               ->addCommand($ar, 'ar')
                               ->runTest($argv, $argc);
        $this->assertEquals(0, $o);
    }

    public function testDefaultCommandGetsNoArgumentsIfAlwaysRunOptionEnabledAndNoDefaultArguments()
    {
        extract($this->generateArgvArgc("ar 1 2 3 4 5"));

        $ar = new CLIArgRepeater;

        // ensure proper arguments to run()
        $def = $this->getMock('CLIArgRepeater', array('testArguments'));
        $def->expects($this->once())
                        ->method('testArguments')
                        ->with($this->equalTo(array()));
        $o = CLImaxController::create()
                               ->setDefaultCommand($def, array('alwaysRuns' => true))
                               ->addCommand($ar, 'ar')
                               ->runTest($argv, $argc);
        $this->assertEquals(0, $o);
    }

    public function testDefaultCommandGetsFirstSetOfArgumentsIfAlwaysRunOptionEnabledAndArgumentsSpecifiedBeforeDefaultCommand()
    {
        extract($this->generateArgvArgc("1 2 ar 1 2 3 4 5"));

        $ar = new CLIArgRepeater;

        // ensure proper arguments to run()
        $def = $this->getMock('CLIArgRepeater', array('testArguments'));
        $def->expects($this->once())
                        ->method('testArguments')
                        ->with($this->equalTo(array(1,2)));
        $o = CLImaxController::create()
                               ->setDefaultCommand($def, array('alwaysRuns' => true))
                               ->addCommand($ar, 'ar')
                               ->runTest($argv, $argc);
        $this->assertEquals(0, $o);
    }

    public function testCommandRunsIfPresentInArgs()
    {
        extract($this->generateArgvArgc("hw"));

        $mock = $this->getMock('CLIHelloWorld', array('run'));
        $mock->expects($this->once())
                        ->method('run')
                        ->will($this->returnValue(0));

        $o = CLImaxController::create()
                               ->addCommand($mock, array('hw'))
                               ->runTest($argv, $argc);
    }

    public function testCommandGetsExpectedArguments()
    {
        extract($this->generateArgvArgc("repeat 1 2 3 4 5"));

        $ar = new CLIArgRepeater;
        // ensure proper arguments to run()
        $ar = $this->getMock('CLIArgRepeater', array('testArguments'));
        $ar->expects($this->once())
                        ->method('testArguments')
                        ->with($this->equalTo(array(1,2,3,4,5)));
        $o = CLImaxController::create()
                               ->addCommand($ar, array('repeat'))
                               ->runTest($argv, $argc);
        $this->assertEquals(0, $o);
    }
}
