#!/usr/bin/env php
<?php
/* vim: set syntax=php expandtab tabstop=4 shiftwidth=4: */

/**
 * This is a climax application. It is used for development of climax.
 */
require_once 'CLImax.php';

// DEFINE COMMANDS
class Usage extends CLIMax_BaseCommand
{
    public function run($arguments, CLImaxController $cliController)
    {
        return $cliController->usage();
    }
}

class CLImaxTest extends CLIMax_BaseCommand
{
    public function run($arguments, CLImaxController $cliController)
    {
        passthru("phpunit . 2>&1", $result);
        return $result;
    }
}

class CLImaxSpec extends CLIMax_BaseCommand
{
    public function run($arguments, CLImaxController $cliController)
    {
        passthru("phpunit --testdox . 2>&1", $result);
        return $result;
    }
}

// WIRE UP APPLICTION
CLImaxController::create()
                  ->addCommand(new Usage, array('-h', '--help', 'help'))
                  ->addCommand(new CLImaxTest, array('test'))
                  ->addCommand(new CLImaxSpec, array('spec'))
                  ->run($argv, $argc);
